<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -dcarbon -vewnhi -l -Fucarbon;carbon/objc;carbon/pascocoa/appkit;carbon/pascocoa/foundation;../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../../components/lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../units/%(CPU_TARGET)-%(OS_TARGET);. -Ficarbon;carbon/objc;carbon/pascocoa/appkit;carbon/pascocoa/foundation lcl.pas"/>
</CONFIG>
