<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -Funumlib_fix;editors;../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);.  -MObjFPC -Scgi -Cr -O1 -g -gl -vewnhi -l tachartlazaruspkg.pas"/>
</CONFIG>
