<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fu../..;../../Parse;../../Parse/PreProcessor;../../Parse/UI;../../Process;../../Process/Align;../../Process/Capitalisation;../../Process/Indent;../../Process/Info;../../Process/Obfuscate;../../Process/Onceoffs;../../Process/Returns;../../Process/Spacing;../../Process/Transform;../../Process/Warnings;../../ReadWrite;../../Settings;../../Settings/Streams;../../Ui;../../Ui/Settings;../../Utils;../../Utils/DragDrop;../../../../packager/units/$(CPU_TARGET)-$(OS_TARGET);../../../lazutils/lib/$(CPU_TARGET)-$(OS_TARGET);../../../../lcl/units/$(CPU_TARGET)-$(OS_TARGET);../../../../lcl/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../../../lazcontrols/lib/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);../../../ideintf/units/$(CPU_TARGET)-$(OS_TARGET)/$(LCL_PLATFORM);. -Fi../../Include;../../Ui/Settings  -MObjFPC -Sgi -O1 -g -gl -l -vewnhibq -dLCL -dLCL$(LCL_PLATFORM) jcfidelazarus.pas"/>
</CONFIG>
