<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Sgi -O1 -gl -vewnhi -l -Fu../../;../../Parse;../../Parse/PreProcessor;../../Parse/UI;../../Process;../../Process/Align;../../Process/Capitalisation;../../Process/Indent;../../Process/Info;../../Process/Obfuscate;../../Process/Onceoffs;../../Process/Returns;../../Process/Spacing;../../Process/Transform;../../Process/Warnings;../../ReadWrite;../../Settings;../../Settings/Streams;../../Ui;../../Ui/Settings;../../Utils;../../Utils/DragDrop;../../../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET);../../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -Fi../../Include;C:/programming/lazarus/components/jcf2/Ui/Settings -dLCL -dLCL%(LCL_PLATFORM) jcfidelazarus.pas"/>
</CONFIG>
