<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Sgi -O1 -g -gl -vewnhi -l -Fu../../;../../Parse;../../Parse/PreProcessor;../../Parse/UI;../../Process;../../Process/Align;../../Process/Capitalisation;../../Process/Indent;../../Process/Info;../../Process/Obfuscate;../../Process/Onceoffs;../../Process/Returns;../../Process/Spacing;../../Process/Transform;../../Process/Warnings;../../ReadWrite;../../Settings;../../Settings/Streams;../../Ui;../../Ui/Settings;../../Utils;../../Utils/DragDrop;C:/lazarus/ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET);C:/lazarus/components/lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);C:/lazarus/packager/units/%(CPU_TARGET)-%(OS_TARGET);. -Fi../../Include;../../Ui/Settings -dLCL -dLCL%(LCL_PLATFORM) jcfidelazarus.pas"/>
</CONFIG>
