<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vewnhi -l -Fucustomdrawn;../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../../components/lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../units/%(CPU_TARGET)-%(OS_TARGET);. -Ficustomdrawn lcl.pas"/>
</CONFIG>
