<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vewnh -l -vm4055,5024 -FuC:/lazarus/components/synedit/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);C:/lazarus/packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) -dgc allsyneditdsgn.pas"/>
</CONFIG>
