<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vewnh -l -vm4055,5024 -Fu../units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) -dgc allsyneditdsgn.pas"/>
</CONFIG>
