<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -Fu../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);.  -MObjFPC -Sci -O1 -g -gl -vewni -l codetools.pas"/>
</CONFIG>
