<?xml version="1.0" encoding="UTF-8"?>
<CONFIG>
  <Makefile Value="2"/>
  <Params Value=" -Fuforms;widgetset;nonwin32;../packager/units/$(CPU_TARGET)-$(OS_TARGET);../components/lazutils/lib/$(CPU_TARGET)-$(OS_TARGET);. -Fiinclude  -MObjFPC -Scghi -O1 -g -gl -vew -l alllclunits.pp"/>
</CONFIG>
