<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vew -l -Fiinclude -Fuforms;widgetset;nonwin32;../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -FUunits/%(CPU_TARGET)-%(OS_TARGET) alllclunits.pp"/>
</CONFIG>
