#
#   $Id$
#
#   Makefile.fpc for Lazarus for Free Pascal
#

[package]
main=lcl

[target]
dirs=gtk gtk2 win32 gnome

[default]
dir=$(LCL_PLATFORM)

[prerules]
# LCL Platform
ifndef LCL_PLATFORM
ifeq ($(OS_TARGET),win32)
LCL_PLATFORM=win32
else
LCL_PLATFORM=gtk
endif
endif
export LCL_PLATFORM
