{ This unit was automatically created by update_allunits }
unit AllLCLIntfUnits;
interface
uses
  interfaces{%H-},
  qt4{%H-},
  qt45{%H-},
  qtcaret{%H-},
  qtint{%H-},
  qtobjects{%H-},
  qtprivate{%H-},
  qtproc{%H-},
  qtsystemtrayicon{%H-},
  qtthemes{%H-},
  qtwidgets{%H-},
  qtwsbuttons{%H-},
  qtwscalendar{%H-},
  qtwschecklst{%H-},
  qtwscomctrls{%H-},
  qtwscontrols{%H-},
  qtwsdesigner{%H-},
  qtwsdialogs{%H-},
  qtwsextctrls{%H-},
  qtwsextdlgs{%H-},
  qtwsfactory{%H-},
  qtwsforms{%H-},
  qtwsgrids{%H-},
  qtwsimglist{%H-},
  qtwsmenus{%H-},
  qtwspairsplitter{%H-},
  qtwsspin{%H-},
  qtwsstdctrls{%H-};
implementation
end.
