<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vewnhi -l -Fufpgui;fpgui/gui;fpgui/corelib;fpgui/corelib/x11;../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../../components/lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../units/%(CPU_TARGET)-%(OS_TARGET);. -Fifpgui;fpgui/gui;fpgui/corelib;fpgui/corelib/x11 -dfpguix11 lcl.pas"/>
</CONFIG>
