#
#   Makefile.fpc for Lazarus for Free Pascal
#

[targets]
dirs=synedit mwedit

[dirs]
# target dir needs to be . or a full path otherwise the 
# unittargetdir will be corrupt
# not with the lazarusmake.ini
# targetdir=.
unittargetdir=./units

[install]
units=$(notdir $(basename $(wildcard $(UNITTARGETDIR)/*$(PPUEXT))))
packagename=components


[presettings]

[postsettings]

[rules]
