{ This unit was automatically created by update_allunits }
unit AllLCLIntfUnits;
interface
uses
  interfaces{%H-},
  win32debug{%H-},
  win32def{%H-},
  win32extra{%H-},
  win32int{%H-},
  win32proc{%H-},
  win32themes{%H-},
  win32wsbuttons{%H-},
  win32wscalendar{%H-},
  win32wschecklst{%H-},
  win32wscomctrls{%H-},
  win32wscontrols{%H-},
  win32wsdialogs{%H-},
  win32wsextctrls{%H-},
  win32wsextdlgs{%H-},
  win32wsfactory{%H-},
  win32wsforms{%H-},
  win32wsgrids{%H-},
  win32wsimglist{%H-},
  win32wsmenus{%H-},
  win32wspairsplitter{%H-},
  win32wsspin{%H-},
  win32wsstdctrls{%H-},
  win32wstoolwin{%H-};
implementation
end.
