{ This unit was automatically created by update_allunits }
unit AllLCLIntfUnits;
interface
uses
  win32wsdialogs,
  win32extra,
  win32wsextdlgs,
  win32wsarrow,
  win32wschecklst,
  win32wsstdctrls,
  win32wscalendar,
  win32def,
  win32wstoolwin,
  win32uxtheme,
  interfaces,
  win32proc,
  win32wspairsplitter,
  win32themes,
  win32wsmenus,
  win32debug,
  win32wscontrols,
  win32wsfactory,
  win32wsextctrls,
  win32wscomctrls,
  win32wsgrids,
  win32wsimglist,
  win32int,
  win32wsspin,
  win32wsbuttons,
  win32wsforms;
implementation
end.
