#   $Id$
#
#   Makefile.fpc for Lazarus for Free Pascal
#

[package]
name=win32interface
version=0.7

[target]
units=interfaces
incdir=.

[compiler]
targetdir=../../units/win32
unitdir=$(TARGETDIR) ../../units

[install]
fpcpackage=n

[default]
fpcdir=C:\FreePascal\cvs\fpc

[prerules]
override FPCOPT+=-gl -Or -S2h

[rules]
all:
        $(MAKE) --assume-new=interfaces$(PASEXT) interfaces$(PPUEXT)
