<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scgi -O1 -gl -vewnhi -l -Fu../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -Fi. -dLCL -dLCL%(LCL_PLATFORM)"/>
</CONFIG>
