<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scgi -O1 -g -gl -vewnhi -l -Fu../lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) printers4lazide.pas"/>
</CONFIG>
