<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -Fu../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../codetools/units/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../synedit/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);.  -MObjFPC -Sgi -O1 -g -gl -vewnhi -l lazsvnpkg.pas"/>
</CONFIG>
