#   $Id$
#
#   Makefile.fpc for Lazarus for Free Pascal
#

[target]

[clean]
files=$(wildcard *$(OEXT)) $(wildcard *$(PPUEXT)) $(wildcard *$(RSTEXT))\
      $(wildcard ./units/*$(OEXT)) \
      $(wildcard ./units/*$(PPUEXT)) \
      $(wildcard ./units/*$(RSTEXT)) \
      $(wildcard ./units/$(CPU_TARGET)-$(OS_TARGET)/*$(OEXT)) \
      $(wildcard ./units/$(CPU_TARGET)-$(OS_TARGET)/*$(PPUEXT)) \
      $(wildcard ./units/$(CPU_TARGET)-$(OS_TARGET)/*$(RSTEXT)) \

[rules]
cleanlaz: clean

# end.

