#   $Id$
#
#   Makefile.fpc for Lazarus for Free Pascal
#

[target]

[clean]
files=$(wildcard ./units/*$(OEXT)) $(wildcard ./units/*$(PPUEXT)) $(wildcard ./units/*$(RSTEXT))

[rules]
cleanall: clean

# end.

