#   $Id$
#
#   Makefile.fpc for Lazarus TGTKGLAreaControl for Free Pascal
#

[package]
name=lazarus-gtkglarea
version=0.8a

[target]
units=gtkglarea
implicitunits=gtkglarea_int nvgl gtkglarea


[default]

            
[compiler]
options=-gl -k-lGL
unitdir=. ../../../lcl/units ../../../lcl/units/gtk

[require]
packages=rtl fcl gtk opengl

[clean]

[install]

[dist]
zipname=lazarus.gtkglarea.$(ZIPSUFFIX)

[rules]
.PHONY: cleartarget all makefile makefiles

all: cleartarget

# end.
