<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -Fu../../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../cairocanvas/lib/%(CPU_TARGET)-%(OS_TARGET);../../lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../printers/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);.  -MObjFPC -Scgi -O1 -g -gl -vewnhi -l turbopoweriprodsgn.pas"/>
</CONFIG>
