<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scgi -O1 -g -gl -vewnhi -l -FuC:/lazarus/ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/components/turbopower_ipro/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../printers/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);C:/lazarus/packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) turbopoweriprodsgn.pas"/>
</CONFIG>
