{ This unit was automatically created by update_allunits }
unit AllLCLIntfUnits;
interface
uses
  gtkwscontrols,
  gtkwspairsplitter,
  gtkwschecklst,
  gtkwsprivate,
  gtkwsextctrls,
  gtkwsgrids,
  gtkint,
  gtkwinapiwindow,
  interfaces,
  gtkwsstdctrls,
  gtkwsfactory,
  gtk1wsprivate,
  gtkwsmenus,
  gtkmsgqueue,
  gtkwsextdlgs,
  gtkglobals,
  gtk1int,
  gtkwsbuttons,
  gtkwsdialogs,
  gtkwsarrow,
  gtkfontcache,
  gtkwsimglist,
  gtkthemes,
  gtkwsspin,
  gtk1def,
  gtkproc,
  gtkwscomctrls,
  gtkwscalendar,
  gtkdef,
  gtkdebug,
  gtkextra,
  gtkwsforms;
implementation
end.
