<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -gl -vew -l -Fu../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -gh -gt -gl -dVerboseIndenter -dQT_NATIVE_DIALOGS -dWithSynOverviewGutter -dLCL -dLCL%(LCL_PLATFORM) ideintf.pas"/>
</CONFIG>
