<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -g -gl -vew -l -Fu../components/lazcontrols/lib/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../components/synedit/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../components/lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -Fiimages -dLCL -dLCL%(LCL_PLATFORM) ideintf.pas"/>
</CONFIG>
