<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scghi -O1 -vewnhi -l -FuC:/lazarus/ideintf/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);C:/lazarus/lcl/units/%(CPU_TARGET)-%(OS_TARGET);C:/lazarus/components/lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);C:/lazarus/packager/units/%(CPU_TARGET)-%(OS_TARGET);. -dLCL -dLCL%(LCL_PLATFORM) instantfpclaz.pas"/>
</CONFIG>
