#   $Id$
#
#   Makefile.fpc for Lazarus for Free Pascal
#

[package]
name=jitform
version=0.9b

[compiler]
unitdir=../../lcl/units .
unittargetdir=../units
options=-gl

[target]
units=jitform

[clean]
files=$(wildcard *$(OEXT)) $(wildcard *$(PPUEXT)) $(wildcard *$(RSTEXT))

[require]
packages=fcl

[default]
lcldir=../../lcl

[rules]
.PHONY: cleartarget all

cleartarget:
        -$(DEL) $(COMPILER_UNITTARGETDIR)/jitform$(PPUEXT)

all: cleartarget jitform$(PPUEXT)

# end.

