<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scgi -O1 -gl -vewnhi -l -Fuunix;win32;carbon;qt;../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../../packager/units/%(CPU_TARGET)-%(OS_TARGET);. -Fiunix;win32;carbon;qt;. -dUseCache -dNativePrint -dLCL -dLCL%(LCL_PLATFORM) printer4lazarus.pas"/>
</CONFIG>
