<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -MObjFPC -Scgi -O1 -g -gl -vewnhi -l -Fuunix;win32;carbon;qt;../../packager/units/%(CPU_TARGET)-%(OS_TARGET);../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET);../../lcl/units/%(CPU_TARGET)-%(OS_TARGET)/%(LCL_PLATFORM);../cairocanvas/lib/%(CPU_TARGET)-%(OS_TARGET);. -Fiunix;win32;carbon;qt  -MObjFPC -Scgi -O1 -g -gl -vewnhi -l printer4lazarus.pas"/>
</CONFIG>
