<?xml version="1.0"?>
<CONFIG>
  <Makefile Value="True"/>
  <Params Value=" -Fu../../packager/registration/lib/%(CPU_TARGET)-%(OS_TARGET)/EnableFurball;../lazutils/lib/%(CPU_TARGET)-%(OS_TARGET)/EnableFurball;../../lcl/lib/%(CPU_TARGET)-%(OS_TARGET)/EnableFurball;../../lcl/interfaces/lib/%(CPU_TARGET)-%(OS_TARGET)/EnableFurball;.  -MObjFPC -Scghi -O1 -g -gl -vewnhi -l cairocanvas_pkg.pas"/>
</CONFIG>
