#   $Id$
#
#   Makefile.fpc for Lazarus for Free Pascal
#

[target]
dirs=jitform

[clean]
files=$(wildcard *$(OEXT)) $(wildcard *$(PPUEXT)) $(wildcard *$(RSTEXT)) \
  $(wildcard ./units/*$(OEXT)) $(wildcard ./units/*$(PPUEXT)) $(wildcard ./units/*$(RSTEXT))

[rules]
cleanlaz: clean
