{ This unit was automatically created by update_allunits }
unit AllLCLIntfUnits;
interface
uses
  {%H-}gtk2cellrenderer{%H-},
  {%H-}gtk2debug{%H-},
  {%H-}gtk2def{%H-},
  {%H-}gtk2extra{%H-},
  {%H-}gtk2fontcache{%H-},
  {%H-}gtk2globals{%H-},
  {%H-}gtk2int{%H-},
  {%H-}gtk2listviewtreemodel{%H-},
  {%H-}gtk2msgqueue{%H-},
  {%H-}gtk2proc{%H-},
  {%H-}gtk2themes{%H-},
  {%H-}gtk2winapiwindow{%H-},
  {%H-}gtk2wsbuttons{%H-},
  {%H-}gtk2wscalendar{%H-},
  {%H-}gtk2wschecklst{%H-},
  {%H-}gtk2wscomctrls{%H-},
  {%H-}gtk2wscontrols{%H-},
  {%H-}gtk2wsdialogs{%H-},
  {%H-}gtk2wsextctrls{%H-},
  {%H-}gtk2wsextdlgs{%H-},
  {%H-}gtk2wsfactory{%H-},
  {%H-}gtk2wsforms{%H-},
  {%H-}gtk2wsgrids{%H-},
  {%H-}gtk2wsimglist{%H-},
  {%H-}gtk2wsmenus{%H-},
  {%H-}gtk2wspairsplitter{%H-},
  {%H-}gtk2wsprivate{%H-},
  {%H-}gtk2wsspin{%H-},
  {%H-}gtk2wsstdctrls{%H-},
  interfaces;
implementation
end.
