{ $Id$ }

// included by gtk2int.pp

{******************************************************************************
                 All GTK2 interface communication implementations.
                   Initial Revision  : Sat Jan 17 19:00:00 2004


  !! Keep alphabetical !!

  Support routines go to gtk2proc.pp

 ******************************************************************************
 Implementation
 ******************************************************************************

 *****************************************************************************
 *                                                                           *
 *  This file is part of the Lazarus Component Library (LCL)                 *
 *                                                                           *
 *  See the file COPYING.LCL, included in this distribution,                 *
 *  for details about the copyright.                                         *
 *                                                                           *
 *  This program is distributed in the hope that it will be useful,          *
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of           *
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.                     *
 *                                                                           *
 *****************************************************************************
}

//##apiwiz##sps##   // Do not remove

{------------------------------------------------------------------------------
  Function: AlignmentCreateHandle
  Params: AAlignment:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.AlignmentCreateHandle(const AAlignment: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ArrowCreateHandle
  Params: AArrow:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ArrowCreateHandle(const AArrow: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: BitBtnCreateHandle
  Params: ABitBtn:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.BitBtnCreateHandle(const ABitBtn: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ButtonCreateHandle
  Params: AButton:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ButtonCreateHandle(const AButton: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: CalendarCreateHandle
  Params: ACalendar:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.CalendarCreateHandle(const ACalendar: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: CheckboxCreateHandle
  Params: ACheckBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.CheckboxCreateHandle(const ACheckBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: CheckListBoxCreateHandle
  Params: ACheckListBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.CheckListBoxCreateHandle(const ACheckListBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: CListBoxCreateHandle
  Params: ACListBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.CListBoxCreateHandle(const ACListBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ColorDialogCreateHandle
  Params: AColorDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ColorDialogCreateHandle(const AColorDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ComboBoxCreateHandle
  Params: AComboBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ComboBoxCreateHandle(const AComboBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: EditCreateHandle
  Params: AEdit:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.EditCreateHandle(const AEdit: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: FileDialogCreateHandle
  Params: AFileDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.FileDialogCreateHandle(const AFileDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: FontDialogCreateHandle
  Params: AFontDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.FontDialogCreateHandle(const AFontDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: FormCreateHandle
  Params: AForm:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.FormCreateHandle(const AForm: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: GroupBoxCreateHandle
  Params: AGroupBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.GroupBoxCreateHandle(const AGroupBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: HintWindowCreateHandle
  Params: AHintWindow:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.HintWindowCreateHandle(const AHintWindow: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ImageCreateHandle
  Params: AImage:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ImageCreateHandle(const AImage: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: LabelCreateHandle
  Params: ALabel:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.LabelCreateHandle(const ALabel: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ListBoxCreateHandle
  Params: AListBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ListBoxCreateHandle(const AListBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ListViewCreateHandle
  Params: AListView:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ListViewCreateHandle(const AListView: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: MainMenuCreateHandle
  Params: AMainMenu:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.MainMenuCreateHandle(const AMainMenu: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: MemoCreateHandle
  Params: AMemo:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.MemoCreateHandle(const AMemo: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: MenuItemCreateHandle
  Params: AMenuItem:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.MenuItemCreateHandle(const AMenuItem: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: NotebookCreateHandle
  Params: ANotebook:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.NotebookCreateHandle(const ANotebook: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: OpenFileDialogCreateHandle
  Params: AOpenFileDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.OpenFileDialogCreateHandle(const AOpenFileDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PageCreateHandle
  Params: APage:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PageCreateHandle(const APage: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PairSplitterCreateHandle
  Params: APairSplitter:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PairSplitterCreateHandle(const APairSplitter: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PairSplitterSideCreateHandle
  Params: APairSplitterSide:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PairSplitterSideCreateHandle(const APairSplitterSide: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PanelCreateHandle
  Params: APanel:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PanelCreateHandle(const APanel: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PopupMenuCreateHandle
  Params: APopupMenu:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PopupMenuCreateHandle(const APopupMenu: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PreviewFileControlCreateHandle
  Params: APreviewFileControl:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PreviewFileControlCreateHandle(const APreviewFileControl: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: PreviewFileDialogCreateHandle
  Params: APreviewFileDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.PreviewFileDialogCreateHandle(const APreviewFileDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ProgressBarCreateHandle
  Params: AProgressBar:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ProgressBarCreateHandle(const AProgressBar: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: RadioButtonCreateHandle
  Params: ARadioButton:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.RadioButtonCreateHandle(const ARadioButton: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: SaveFileDialogCreateHandle
  Params: ASaveFileDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.SaveFileDialogCreateHandle(const ASaveFileDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ScrollBarCreateHandle
  Params: AScrollBar:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ScrollBarCreateHandle(const AScrollBar: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ScrollBoxCreateHandle
  Params: AScrollBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ScrollBoxCreateHandle(const AScrollBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ScrolledWindowCreateHandle
  Params: AScrolledWindow:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ScrolledWindowCreateHandle(const AScrolledWindow: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: SelectDirectoryDialogCreateHandle
  Params: ASelectDirectoryDialog:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.SelectDirectoryDialogCreateHandle(const ASelectDirectoryDialog: TObject): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: SpeedButtonCreateHandle
  Params: ASpeedButton:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.SpeedButtonCreateHandle(const ASpeedButton: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: SpineditCreateHandle
  Params: ASpinEdit:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.SpineditCreateHandle(const ASpinEdit: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: StatusBarCreateHandle
  Params: AStatusBar:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.StatusBarCreateHandle(const AStatusBar: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ToggleBoxCreateHandle
  Params: AToggleBox:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ToggleBoxCreateHandle(const AToggleBox: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ToolbarCreateHandle
  Params: AToolbar:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ToolbarCreateHandle(const AToolbar: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: ToolButtonCreateHandle
  Params: AToolButton:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.ToolButtonCreateHandle(const AToolButton: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: TrackBarCreateHandle
  Params: ATrackBar:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.TrackBarCreateHandle(const ATrackBar: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;

{------------------------------------------------------------------------------
  Function: WincontrolCreateHandle
  Params: AFixed:
          AParams:
  Returns:

 ------------------------------------------------------------------------------}
function TGTK2Object.WincontrolCreateHandle(const AFixed: TObject; const AParams: TCreateParams): THandle;
begin
  // Your code here
end;


//##apiwiz##eps##   // Do not remove, no wizard declaration after this line

{ =============================================================================

  $Log $
}
