.TH "lazres" "1" "07 December 2008" "Lazarus" "Lazarus Resource Builder"
.SH "NAME"
lazres \- The Lazarus resource builder.

.SH "SYNOPSIS"
.B lazres
.I resourcefilename filename1 [filename2 ... filenameN]
.br
.B lazres
.I resourcefilename @filelist

.SH "DESCRIPTION"
.B lazres
builds resources for a Lazarus project or package.

.SH "OPTIONS"
.TP 
.BI "\-h"
Displays a short help message.

.SH "SEE ALSO"
.IP 
.BR lazarus\-ide (1)
.BR startlazarus (1)
.BR lazbuild (1)
.BR fpc (1)
.BR ld (1)
.BR fpcmake (1)
.BR make (1)

.SH "Websites"
.IP 
.BR  http://www.lazarus.freepascal.org

