.TH "lrstolfm" "1" "07 December 2008" "Lazarus" "Lazarus Resource Translator"
.SH "NAME"
lrstolfm \- The Lazarus resource Translator.

.SH "SYNOPSIS"
.B lrstolfm
.I resourcefilename [resourcename]

.SH "DESCRIPTION"
.B lrstolfm
Creates an LFM file from resources for a Lazarus project or package (LRS).

.SH "OPTIONS"
No option. If called without any argument it gives a short help message.

.SH "SEE ALSO"
.IP 
.BR lazarus\-ide (1)
.BR startlazarus (1)
.BR lazbuild (1)
.BR fpc (1)
.BR ld (1)
.BR fpcmake (1)
.BR make (1)

.SH "Websites"
.IP 
.BR  http://www.lazarus.freepascal.org

