.TH startlazarus 1 "19 April 2008" "Lazarus" "Lazarus starter"
.SH NAME
startlazarus \- starts lazarus program. 
.B fpdoc.

.SH SYNOPSIS

.B "lazarus"

.SH Description

.B startlazarus
is used to start the lazarus-ide program.

.SH Usage

You can invoke 
.B startlazarus
without any arguments.

.SH SEE ALSO
.IP 
.BR lazarys (1)
.BR lazbuild (1)
.BR fpc (1)
