.TH "startlazarus" "1" "19 April 2008" "Lazarus" "Lazarus starter"
.SH "NAME"
startlazarus \- starts lazarus program.
.B fpdoc.

.SH "SYNOPSIS"
.B "lazarus"

.SH "Description"
.B startlazarus
is used to start the lazarus program. It automatically checks if the user has
built a custom lazarus and starts it. It is also used to restart the IDE, when
the user clicks restart in the IDE.

.SH "Usage"
You can invoke 
.B startlazarus
without any arguments.

.SH "SEE ALSO"
.IP 
.BR lazarus\-ide (1)
.BR lazbuild (1)
.BR fpc (1)
