.TH "updatepofiles" "1" "07 December 2008" "Lazarus" "Lazarus Translation Tool"
.SH "NAME"
updatepofiles \- The Lazarus resource builder.

.SH "SYNOPSIS"
.B updatepofiles
.I filename1.po [filename2.po ... filenameN.po]

.SH "DESCRIPTION"
.B updatepofiles
Update internationalization files.

.SH "OPTIONS"
No option. If called without any argument it gives a short help message.

.SH "SEE ALSO"
.IP 
.BR lazarus\-ide (1)
.BR startlazarus (1)
.BR lazbuild (1)
.BR fpc (1)
.BR ld (1)
.BR fpcmake (1)
.BR make (1)

.SH "Websites"
.IP 
.BR  http://www.lazarus.freepascal.org

